manager/urls.py
# -*- coding: utf-8 -*-
"""Proyect url's."""

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'manager.magazine_views',
    url(r'^$', 'IndexView', name='inicio'),
    url(r'^home/$', 'HomeView', name='home'),
    url(r'^articulos/$', 'ArtView', name='articulos'),
    url(r'^formarticulo/$', 'FormArtView', name='formarticulo'),
    url(r'^addarticulo/$', 'AddArtView', name='addarticulo'),
    url(r'^addautorart/$', 'AddAuartView', name='addautorart'),
    url(r'^rmautorart/$', 'RmAuartView', name='rmautorart'),
    url(r'^crop/$', 'crop', name='crop'),
    url(r'^getarticulos/$', 'getArtView', name='getarticulos'),
    url(r'^addphoto/$', 'addphoto', name='addphoto'),
    url(r'^muser/$', 'muser', name='muser'),
)



urlpatterns += patterns(
    'manager.autores_views',
    url(r'^autores/$', 'AutoresView', name='autores'),
    url(r'^getautores/$', 'getAutoresView', name='getautores'),
    url(r'^formautor/$', 'FormAutorView', name='formautor'),
    url(r'^addautor/$', 'addAutorView', name='addautor'),

)


urlpatterns += patterns(
    'manager.empresas_views',
    url(r'^empresas/$', 'EmpresasView', name='empresas'),
    url(r'^getempresas/$', 'getEmpresasView', name='getempresas'),
    url(r'^formempresa/$', 'FormEmpresaView', name='forempresa'),
    url(r'^addempresa/$', 'addEmpresaView', name='addempresa'),

)


urlpatterns += patterns(
    'manager.categoria_magazine_views',
    url(r'^categorias/$', 'CatView', name='categorias'),
    url(r'^getcats/$', 'getCatView', name='getcats'),
    url(r'^formcats/$', 'FormCatView', name='formcats'),
    url(r'^addcat/$', 'addCatView', name='addcat'),

)


urlpatterns += patterns(
    'manager.capsulas_views',
    url(r'^capsulas/$', 'CapsulasView', name='capsulas'),
    url(r'^getcapsulas/$', 'getCapsulasView', name='getcapsulas'),
    url(r'^formcapsulas/$', 'FormCapsulasView', name='formcapsulas'),
    url(r'^addcapsulas/$', 'addCapsulaView', name='addcapsulas'),

)


urlpatterns += patterns(
    'manager.videos_views',
    url(r'^videos/$', 'VideosView', name='videos'),
    url(r'^getvideos/$', 'getVideosView', name='getvideos'),
    url(r'^formvideos/$', 'FormVideosView', name='formvideos'),
    url(r'^addvideos/$', 'addVideosView', name='addvideos'),

)


urlpatterns += patterns(
    'manager.jlong_views',
    url(r'^jimlong/$', 'JimlongView', name='jimlong'),
    url(r'^getjimlong/$', 'getJimlongView', name='getjimlong'),
    url(r'^formjimlong/$', 'FormVideosView', name='formjimlong'),
    url(r'^addjimlong/$', 'addJimlongView', name='addjimlong'),

)


#----------------------------------------------__EMPRESAS
#----------------------------------------------CATEGORIAS

urlpatterns += patterns(
    'manager.dempresa.categorias_views',
    url(r'^catempresas/$', 'CatEmView', name='catempresas'),
    url(r'^getcatempresas/$', 'getCatEmView', name='getcatempresas'),
    url(r'^formcatempresas/$', 'FormCatEmView', name='formcatempresas'),
    url(r'^addcatempresas/$', 'addCatEmView', name='addcatempresas'),

)


#------------------------------------------------EMPRESAS
#-----------------------------------------------PRODUCTOS

urlpatterns += patterns(
    'manager.dempresa.productos_views',
    url(r'^productos/$', 'ProductoView', name='productos'),
    url(r'^getproductos/$', 'getProductoView', name='getproductos'),
    url(r'^formproductos/$', 'FormProductoView', name='formproductos'),
    url(r'^addproducto/$', 'addProductoView', name='addproducto'),

)


#-----------------------------------------------------------------EMPRESAS
#---------------------------------------------------------------CONTATCTOS

urlpatterns += patterns(
    'manager.dempresa.contactos_views',
    url(r'^contactos/$', 'ContactoView', name='contactos'),
    url(r'^getcontactos/$', 'getContactoView', name='getcontactos'),
    url(r'^formcontacto/$', 'FormContactoView', name='formcontacto'),
    url(r'^addcontacto/$', 'addContactoView', name='addcontacto'),

)


#-------------------------------------------------------------- BANNERS
#---------------------------------------------------------------BANNERS

urlpatterns += patterns(
    'manager.banners.banners_views',
    url(r'^banners/$', 'BannerView', name='banners'),
    url(r'^getbanners/$', 'getBannerView', name='getbanners'),
    url(r'^formbanners/$', 'FormBannerView', name='formbanners'),
    url(r'^addbanner/$', 'addBannerView', name='addbanner'),

)


#-------------------------------------------------------------- EVENTOS
#---------------------------------------------------------------EVENTOS

urlpatterns += patterns(
    'manager.eventos.eventos_views',
    url(r'^eventos/$', 'EventosView', name='eventos'),
    url(r'^geteventos/$', 'getEventosView', name='geteventos'),
    url(r'^formeventos/$', 'FormEventosView', name='formeventos'),
    url(r'^addevento/$', 'addEventoView', name='addevento'),

)



#-------------------------------------------------------------- SECCIONES
#---------------------------------------------------------------EVENTOS

urlpatterns += patterns(
    'manager.secciones_views',
    url(r'^secciones/$', 'SeccionesView', name='secciones'),
    #url(r'^geteventos/$', 'getEventosView', name='geteventos'),
    url(r'^formsecciones/$', 'FormSeccionView', name='formsecciones'),
    url(r'^addseccion/$', 'addSeccionView', name='addseccion'),

)

pecuarios/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

'''
from restapp.views import ArtViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'rest_articulos', ArtViewSet)
#router.register(r'autores', AutorViewSet)
'''


urlpatterns = [

    url(r'^manager/', include('manager.urls')),
    url(r'^rest/', include('restapp.urls')),
    url(r'^', include('webapp.urls')), 
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^', include(router.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'webapp.views',
    url(r'^$', 'IndexView', name='inicio'),
    url(r'^google9961f820608b1944.html$', 'anview', name='google9961f820608b1944.html'),
    url(r'^single/(?P<slugg>[-\w]+)$', 'SingleView', name='SingleView'),
    #url(r'^getarticulos/$', 'getArtView', name='getarticulos'),
)

manager/models.py
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.sites.models import Site
from django.contrib.auth.models import User
import simplejson


STATUS = (
        ('1','Fuera de línea'),
        ('2','En espera de aprobación'),
        ('3','En línea'),
)


USUARIOS = (
    ('contacto','Contacto'),
    ('autor','Autor'),
)


AUTORES = (
    ('Autor','Autor'),
    ('Co-Autor','Co-Autor'),
    ('Colaborador','Colaborador'),
    ('Fuente','Fuente'),
)

TIPO_PUBLICACION = (
    ('articulo','Artículo'),
    ('noticia','Noticia'),
)



EMPRESAS_NIVEL = (

        ('diamante','Diamante'),
        ('oro','Oro'),
        ('plata','Platino'),
        ('platino','Platino'),
        ('sin nivel','sin nivel'),

    )



SECCIONES = (
    ('home','HOME'),
    ('seccion','SECCIÓN'),
    ('contenido','CONTENIDO'),

    )

TIPO_BANNER = (
    ('728x90','728x90'),
    ('200x200','200x200'),
    ('880x495','880x495'),
    )




TIPO_IMAGEN = (
            ('logo','Logo'),
            ('logo_reporteador','Logo Reporteador'),
            ('bannermicrositio','Baner Micositio'),
            ('imagenmicrositio','Imagen Micrositio'),
            ('pos1','BAN_ALT_POS1'),
            ('pos2','BAN_ALT_POS2'),
            ('pos3','BAN_ALT_POS3'),
            ('pos4','BAN_ALT_POS4'),
            ('pos5','BAN_ALT_POS5'),
            ('pos6','BAN_ALT_POS6'),
            ('pos7','BAN_ALT_POS7'),            
    )


BANNER_VISIBLE = (

    ('web','En la Web'),
    ('movil',u'Móvil'),
    ('ambos',u'Ambos(web y móvil)'),
    )


TIPO_VACANTE = (
    ('solicitante','Solicitante'),
    ('vacante','Vacante'),
    )

TIPOS_PRODUCTO = (

    ('publicacion',u'Publicación'),
    ('producto',u'Producto'),
    )



# --------------------------------------------------------  MODELS PARA LAS SECCIONES
# -----------------------------------------------------------------------------------

class Seccion(models.Model):
    slug = models.CharField(max_length=500)
    fotoprincipal = models.CharField(u'Logo', max_length=255, blank=True, null=True)
    titulo_seccion = models.CharField(u'Nombre Seccion', max_length=255) 
    seccion = models.CharField(u'Sección', max_length=255,choices=SECCIONES) 
    link = models.CharField(u'Link', max_length=500,blank=True,null=True) 
    desc_sec = models.TextField(u'Descripción')
    portal_seccion = models.ForeignKey(Site)    
    fecha_alta = models.DateTimeField(auto_now_add=True)
    fecha_des_beg = models.DateField(u'Fecha destacado inicio',blank=True,null=True)  
    fecha_des_end = models.DateField(u'Fecha destacado final',blank=True,null=True)
    status = models.CharField(u'Estatus',max_length=100,choices=STATUS,default=1)
    vistas = models.DecimalField(u'Visitas',max_digits=18,decimal_places=0,blank=True,null=True)  

    def  __unicode__(self):
        return '%s'%self.titulo_seccion





# ------------------------------------  MODELS PARA LA SECCION DE EMPRESA Y PRODUCTOS
# -----------------------------------------------------------------------------------

class Empresa(models.Model):
    slug_empresa = models.CharField(max_length=500)
    nombre_empresa = models.CharField(u'Nombre Empresa', max_length=255) 
    portal_empresa = models.ForeignKey(Site)
    categoria = models.ForeignKey('CategoriaMagazine',blank=True,null=True)  
    desc_empresa = models.TextField(u'Descripción')
    direcc = models.CharField(u'Dirección', max_length=400)
    cp = models.CharField(u'CP', max_length=10)
    tels = models.CharField(u'Tel', max_length=255, blank=True, null=True)
    fax = models.CharField('FAX', max_length=255, blank=True, null=True)
    web = models.CharField('WEB', max_length=900, blank=True, null=True)
    cve_pais = models.ForeignKey('TblPaises', blank=True, null=True)  
    cve_estado = models.ForeignKey('TblEstados', blank=True, null=True)  
    email = models.CharField(u'email', max_length=6000, blank=True, null=True)
    fotoprincipal = models.CharField(u'Logo', max_length=255, blank=True, null=True)
    fecha_alta = models.DateTimeField(auto_now_add=True)
    status = models.CharField(u'Estatus',max_length=100,choices=STATUS,default=1)
    vistas = models.DecimalField(u'Visitas',max_digits=18,decimal_places=0,blank=True,null=True)  
    votacion = models.DecimalField(u'Votos', max_digits=18, decimal_places=0,blank=True,null=True) 
    numvotos = models.DecimalField(u'num Votos', max_digits=18, decimal_places=0,blank=True,null=True)
    privado = models.BooleanField(u'Privado',default=0)
    redes = models.TextField('Redes',blank=True,null=True)
    nivel_empresa = models.CharField(u'Nivel Empresa',max_length=100,choices=EMPRESAS_NIVEL)
    latitud = models.CharField(u'Latitud', max_length=255, blank=True, null=True)
    longitud = models.CharField(u'Longitud', max_length=255, blank=True, null=True)


    def  __unicode__(self):
        return '%s'%self.nombre_empresa

class Galeriaempresas(models.Model):
    empresa_own = models.ForeignKey(Empresa)
    tipoimagen = models.CharField(u'Tipo',max_length=100,choices=TIPO_IMAGEN)
    imagen = models.ImageField(u'Imagen', max_length=500, blank=True, null=True)
    link = models.CharField(u'Link imagen',max_length=500,blank=True,null=True)

class Contactoempresa(models.Model):
    empresapk = models.ForeignKey(Empresa,verbose_name='Empresa')
    slug = models.CharField(max_length=500)
    nombre_contacto = models.CharField(u'Nombre',max_length=200)
    email_contacto = models.EmailField(u'Correo Electrónico',max_length=500)
    #redes = models.TextField('Redes',blank=True,null=True)
    fotoprincipal = models.CharField(u'Logo', max_length=255, blank=True, null=True)
    cve_pais = models.ForeignKey('TblPaises', blank=True, null=True)  
    cve_estado = models.ForeignKey('TblEstados', blank=True, null=True)  

class Catprods(models.Model):
    slug = models.CharField(max_length=500)
    nombre_categoria = models.CharField(u'Nombre Categoría', max_length=255) 
    parentcat = models.ForeignKey('Catprods',blank=True,null=True) 
    portal = models.ManyToManyField(Site,verbose_name='Portal', blank=True, null=True)  
    fecha_alta = models.DateTimeField('Fecha Alta',auto_now_add=True)  
    imagen = models.ImageField('Imagen',upload_to='static/categoria_productos/', blank=True, null=True)  
    
    def __unicode__(self):
        return self.nombre_categoria


class Producto(models.Model):
    slug = models.CharField(max_length=500)
    nombre = models.CharField('Nombre Producto', max_length=255)  
    portal = models.ForeignKey(Site,verbose_name='Portal')  
    tipo = models.CharField(u'Tipo Producto',max_length=100,choices=TIPOS_PRODUCTO)
    empresapk = models.ForeignKey(Empresa,verbose_name='Empresa', blank=True,null=True)  
    cvecat = models.ManyToManyField('Catprods')  
    tipo = models.IntegerField('TIPO', blank=True, null=True)  
    resenia = models.TextField(u'Reseña', blank=True, null=True)  
    liga = models.CharField('link', max_length=900, blank=True, null=True)  
    fecha_alta = models.DateTimeField('Fecha Alta',auto_now_add=True)  
    status = models.CharField(u'Estatus',default=1,max_length=10,choices=STATUS) 
    email = models.EmailField('Correo Electrónico', max_length=255, blank=True, null=True)  
    descrip = models.TextField('Descripción')  
    vistas = models.IntegerField(u'Visitas',default=0, blank=True, null=True)  
    vistasapp = models.IntegerField(u'Visitas',default=0, blank=True, null=True)  
    votacion = models.DecimalField(u'Votos', max_digits=18, decimal_places=0,default=0, blank=True, null=True)  
    numvotos = models.IntegerField(u'num Votos',default=0,blank=True, null=True) 
    fotoprincipal = models.CharField(u'Foto principal',max_length=600)
    privado = models.BooleanField(u'Contenidop Privado',default=0)
    likes = models.IntegerField(u'likes',default=0)

class Prodcontacto(models.Model):
    productopk=models.ForeignKey(Producto)
    contactopk = models.ForeignKey(Contactoempresa)

class Likeproducto(models.Model):
    productopk  = models.ForeignKey(Producto)
    usuarioreg = models.ForeignKey('TblRegs',blank=True, null=True)
    fecha = models.DateTimeField('fecha',auto_now_add=True)  



# ------------------------------------  MODELS PARA LA SECCION DE MAGAZINE 
# ------------------------------------------------------------------------

class CategoriaMagazine(models.Model):
    nombre_categoria = models.CharField(u'categoría',max_length=255)
    fechapub = models.DateTimeField(auto_now_add=True)
    portal = models.ManyToManyField(Site)
    actv = models.BooleanField(u'Activado',default=1)

    def __unicode__(self):
        return '%s'%self.nombre_categoria


class Articulos(models.Model):
    slug = models.CharField(max_length=500)
    nombre_articulo = models.CharField(u'Título', max_length=500)
    fechapub = models.DateTimeField(u'Fecha de Publicación')
    portal_articulo = models.ForeignKey(Site,verbose_name='Portal')
    cve_empresa = models.ForeignKey(Empresa,verbose_name='Empresa', blank=True,null=True)
    cve_cat = models.ManyToManyField(CategoriaMagazine,verbose_name=u'Categoría')
    texto = models.TextField(u'Texto Corto',blank=True,null=True)
    descrip = models.TextField(u'Contenido')
    fecha_alta = models.DateTimeField(u'Fecha de alta',auto_now_add=True)  
    fecha_des_beg = models.DateField(u'Fecha destacado inicio',blank=True,null=True)  
    fecha_des_end = models.DateField(u'Fecha destacado final',blank=True,null=True)
    status = models.CharField(u'Estatus',default=1,max_length=10,choices=STATUS) 
    tipo = models.CharField(u'Tipo Publicación',max_length=100,choices=TIPO_PUBLICACION)  
    vistas = models.IntegerField(u'Visitas',default=0)  
    vistasapp = models.IntegerField(u'Visitas',default=0)  
    votacion = models.DecimalField(u'Votos', max_digits=18, decimal_places=0,default=0)  
    numvotos = models.IntegerField(u'num Votos',default=0) 

manager/views.py
# -*- coding: utf-8 -*-


from django.http import HttpResponse
from django.shortcuts import redirect, render, render_to_response
from django.template.context import RequestContext
from django.views.generic import View


class IndexView(View):
    """View to retrieve companies list."""

    template = 'manager/index.html'

    def get(self, request):
        """Retrieve the list of the all companies."""
        page = request.GET.get('page', 1)
        portal = request.GET.get('portal', None)

        if portal is None:
            response = render(request, self.template, None)
            return response

        context = {}

        context['empresas'] = ['a','b']
        context['total_empresas'] = 100

        response = render(request, self.template, context)
        return response

manager/templates/manager/empresa/categorias/formulario.html
{% extends 'manager/base.html'%}


{% block extras %}
    <link href="/static/css/crop/croppic.css" rel="stylesheet"></link>
    <link href="/static/css/manager_magazine.css" rel="stylesheet"></link>
    <style>
.lb{
    display: inline-block;vertical-align: middle;
}



.smallinput{
font-family: 'Raleway', sans-serif;
padding:3vmin;font-size:1vmax;margin:auto;
border-bottom-right-radius:2.5vmin;
border-top-left-radius:1vmin;
color:#333;font-weight:400;
width:90%;margin:1vmin 0px;
background:#EEE;
}


.roundlogop{
    width:12vmin;height:12vmin;
    border-radius:10vmin;
    background-size: cover;
    background-color:#666;
    margin:2vmin auto;

}

.minigallery{
    width:15%;height:auto;padding:2px;
    background-size: cover;background-repeat: no-repeat;
    border-top-left-radius: 2vmin;
    margin:1vmin;
    word-wrap: break-word;
    vertical-align: top;
}




    </style>
{% endblock %}

{% block content %}

<form id="addphoto_form" method='post'>
  {% csrf_token %}
  <input type="hidden" name="idnoticia" id="idnoticia" value="{{id}}" />
  <input type="file" name="foto" id="galery" style="display:none;" />
</form>

        <!-- BEGIN CONTAINER -->
        <div class="page-container" ng-app='magazineApp'>
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <div class="container">
                    </div>
                </div>
                <!-- END PAGE HEAD-->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content">
                    <div class="container">
                        <!-- BEGIN PAGE BREADCRUMBS -->
                        <ul class="page-breadcrumb breadcrumb">
                            <li>
                                <a href="index.html">Empresas</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <span>Categoría de productos</span>
                            </li>
                        </ul>
                        <!-- END PAGE BREADCRUMBS -->
                        <!-- BEGIN PAGE CONTENT INNER -->
                        <div class="page-content-inner">
                        <div class="row">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="col-md-9 ">
                                <div class="portlet light ">
                                    <div class="portlet-title">
                                        <div class="caption font-red-sunglo">
                                            <i class="glyphicon glyphicon-list-alt"></i>
                                            <span class="caption-subject bold uppercase"> EMPRESAS - CATEGORÍA DE PRODUCTOS</span>
                                        </div>
                                        <div class="actions">
                                           

                                        </div>
                                    </div>
                                    <div class="portlet-body form">

                                        <form role="form" name="articulo" action="/manager/addcatempresas/" method="POST" class="sendit">
                                            {% csrf_token %}
                                          
                                            
                                            <input type="hidden" name="id" id="id_id" {% if id %}value="{{id}}" {% endif %}/>
                                            
                                            <div class="form-body">

                                                <div>
                                                </div>
                                                <div class="form-group" style="display: none;">
                                                    <label class="control-label" for="select2-single-append">Fecha destacado</label>
                                                    <div class="input-group select2-bootstrap-prepend">
                                                        <span class="input-group-addon"><input type="checkbox" > </span>
                                                        <input type="text" placeholder="Destacado" id="demo" class="form-control" value="">
                                                        
                                                    </div>
                                                </div>


                                                {% for p in forma.visible_fields %}
                                                    {% ifequal p.label 'Contenido' %}
                                                    

                                                        <div style="width:100%;">
                                                            <ul id="galeria" class="lb" style="width:90%;">
                                                            {% for f in fotos %}
                                                                <li class="lb minigallery">
                                                                  <p style="display:none;position:absolute;margin-left:11vmin;margin-top:-4vmin;">
                                                                    <a href="#close" class="btn btn-info cancel_close">
                                                                      <i class="fa fa-times"></i>
                                                                    </a>
                                                                  </p>
                                                                  <p>
                                                                      <img src="/{{f.foto}}" width="100%" />
                                                                  </p>
                                                                  <div>
                                                                      /{{f.foto}}
                                                                  </div>
                                                                </li>



                                                            {% endfor %}
                                                            </ul>
                                                            <span class="lb" style="width:9%;text-align:right;">
                                                                <a href="#change" id="addphoto" class="btn btn-info">
                                                                    <i class="fa fa-camera"></i>
                                                                </a>
                                                            </span>
                                                          
                                                        </div>

                                                        <br/>
                                                    {% endifequal %}
                                                    <p>
                                                        <label>{{p.label}}:</label>
                                                        {{p}}
                                                    </p>
                                                {% endfor %}
                                                {% for hidden in forma.hidden_fields %}
                                                {{ hidden }}
                                                {% endfor %}
                                                
            

                                            </div>
                                            <div class="form-actions noborder">
                                                <button type="submit" class="btn blue">Submit</button>
                                                <button type="button" class="btn default">Cancel</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>


                        </div>

                        </div>
                        <!-- END PAGE CONTENT INNER -->
                        </div>
                        <!-- END PAGE CONTENT INNER -->
                    </div>
                </div>
                <!-- END PAGE CONTENT BODY -->
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->


{% endblock %}


{% block extrajs %}

        <script type="text/javascript">
            

                function addphoto(e){
                    e.preventDefault();
                    $('#galery').click();
                }


                function addingthephoto(e){
                    forma = $('#addphoto_form').get(0);
                    var data = new FormData(forma);
                    $.ajax({url:'/manager/addphoto/',
                            type:'POST',
                            data:data,
                            cache: false,
                            processData: false,
                            contentType:false,
                            dataType: 'json',
                            success:function(response){
                                imagen = document.createElement('li');
                                $(imagen).addClass('lb minigallery').attr('ruta',response.path);
                                $(imagen).append('<p><img src="/'+response.path+'" width="100%" /><p>/'+response.path+'</p>');
                                
                                //$(imagen).click(showme);
                                $('#galeria').append(imagen);
                            }

                    });

                }


            function showme(e){
                mypath = $(this).attr('ruta'); 
                // find('img:first').attr('src');
                $('#pather').text('/'+mypath);

            }

            var cropperOptions = {
                  processInline:true,
                  cropData:{
                    "uid":'{{id}}',
                    "portal":'1',
                    "tipo":'capsula',
                  },
                  loaderHtml:'<i class="fa fa-spinner"></i>',
                  //loadPicture:'/static/imgs/{{data.fotoprincipal}}',
                  cropUrl:'/manager/crop/',
                  rotateControls:true,
                  doubleZoomControls:true,
                  imgEyecandy:true,
                  imgEyecandyOpacity:0.2,
                  outputUrlId:'salida',
                  onAfterImgCrop:function(response){
                    $('#id_fotoprincipal').val(response.url);
                    //$('#principalpic img').remove();
                  
                  }
                };

        </script>

        <script src='//cdn.tinymce.com/4/tinymce.min.js'></script>
        <script src="/static/js/chumbucket.js"></script>
        <script src="/static/manager/magazine/magazine-controlers.js"></script>
        <script src="/static/js/crop/croppic.js"></script>
        <script type="text/javascript">
            
  $(document).ready(function(){


    $('.id_privado').prop('indeterminate', true);

    $('#id_fecha').daterangepicker(
    {
        singleDatePicker: true,
        showDropdowns: true,
        locale: {
            format: 'YYYY-MM-DD h:mm'
        }
    }
    );


    $('#demo').daterangepicker({}, function(start, end, label) {
      $('#id_fecha_des_beg').val(start.format('YYYY-MM-DD'));
      $('#id_fecha_des_end').val(end.format('YYYY-MM-DD'));

    });

    var cropperHeader = new Croppic('principalpic',cropperOptions);


    var params = {};

    $('.dropmenuaction li a').click(function(e){
        e.preventDefault();
        params.catpk = $(this).attr('href').replace('#','');
        params.name = $(this).text();
        params.value=$(this).attr('data');
        params.targetx = $(this).parents('ul:first').attr('vic');
        params.input = $(this).parents('ul:first').attr('data-input');
        $('#'+params.targetx).html(params.name);
        $('#'+params.input).val(params.value);

    });

  tinymce.init({
    selector: '#id_descrip',
    plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
  ]
  });



    // AJAX SEND DATA .--------------------------------------------------------
    // REQUIRE chumbucket.js file instead avobe this lines
    $('.sendit').submit(sendit);




  $('#addphoto').click(addphoto);
  $('#galery').change(addingthephoto);



  });

        </script>
{% endblock %}